module.exports = {
    SEARCH_HEADLINES: 'SEARCH_HEADLINES',
    SEARCH_TOP: 'SEARCH_TOP',
    SEARCH_POPULAR: 'SEARCH_POPULAR',
    SEARCH_SPECIFIC: 'SEARCH_SPECIFIC',
    SOURCES:'SOURCES',
    RECEIVE_HEADLINES: 'RECEIVE_HEADLINES',
    RECEIVE_SOURCES: 'RECEIVE_SOURCES',
    RECEIVE_SPECIFIC: 'RECEIVE_SPECIFIC',
    BLANK:'BLANK',
    SBLANK:'SBLANK',
    SOBLANK:'SOBLANK'
}
